---

- name: Create haproxy config directory
  file: path={{ config_dir }} state=directory mode="u=rwx,g=xr,o=x"
  tags:
    - haproxy
    - deploy

- name: Enable haproxy on startup
  copy: src=default.cfg dest={{ config_dir }} mode="u=rx,g=rx,o=rx"

- name: Configure haproxy instance
  template: src=haproxy.cfg.j2 dest={{ config_dir }}/haproxy.cfg owner=root group=root mode=0644

- name: Stop haproxy docker containers
  tags:
    - haproxy
    - deploy
    - just-restart
    - just-stop
  docker:
    name: "{{ item.name }}"
    image: "{{ haproxy_image }}"
    state: stopped
  with_items: haproxy_instances

- name: Start haproxy using docker
  tags:
    - haproxy
    - deploy
    - just-restart
  docker:
    name: "{{ item.name }}"
    image: "{{ haproxy_image }}"
    state: reloaded
    restart_policy: always
    ports:
    - "{{ http_port }}:{{ item.http_port }}"
    - "{{ https_port }}:{{ item.https_port }}"
    volumes:
    - "{{ config_dir }}/default.cfg:{{ haproxy_default_config }}"
    - "{{ config_dir }}:{{ haproxy_config_dir }}"
    - "{{ log_dir }}:/dev/log"
  with_items: haproxy_instances