---

- name: Check if nginx docker image is present
  shell: "docker images -q {{ nginx_image }}"
  register: is_nginx_image_present
  tags:
    - nginx
    - provision

- name: Download nginx image if it's not present
  shell: "docker pull {{ nginx_image }}"
  tags:
    - nginx
    - provision
  when: is_nginx_image_present.stdout == ""
