---

logstash_cert: "{{ app_root_dir }}/logstash-fwd/ssl"

config_dir: "{{ app_root_dir }}/logstash-fwd/conf"
remote_config_dir: /etc/logstash-forwarder

log_dir: "{{ log_root_dir }}/logstash-fwd"

nginx_log_dirs:
  - "{{ log_root_dir }}/lb/*.log"
  - "{{ log_root_dir }}/fe/*.log"

